language: python
jobs:
  include:
    - name: "Python 3.8.0 on Xenial Linux"
      dist: xenial
      python: 3.8           # this works for Linux but is ignored on macOS or Windows
      env:
        - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
        - SEGFAULT_SIGNALS=all
        - LANG=en_US.UTF-8
      before_install:
        - python --version
        - uname -a
      cache: false
    - name: "Python 3.8.0 on macOS"
      os: osx
      osx_image: xcode11.3  # Python 3.8.0 running on macOS 10.14.6
      language: shell       # 'language: python' is an error on Travis CI macOS
      env:
        - LANG=en_US.UTF-8
        - PATH=$HOME/.pyenv/bin:$PATH
      before_install:
        - eval "$(pyenv init -)"
        - eval "$(pyenv virtualenv-init -)"
        - pyenv install -s 3.8.0
        - pyenv global 3.8.0
        - python --version
        - uname -a
      cache:
        directories:
          - /Users/travis/.pyenv/versions
#    - name: "Python 3.8.0 on Windows"
#      os: windows           # Windows 10.0.17134 N/A Build 17134
#      language: shell       # 'language: python' is an error on Travis CI Windows
#      before_install:
#        - choco install python --version 3.8.0
#        - python -m pip install --upgrade pip
#      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
install:
  - python -mpip install --progress-bar=off --upgrade pip
  - python -mpip install --progress-bar=off tox
  - pyenv rehash
  - pip --version
  - virtualenv --version
  - tox --version
script:
  - tox -v
after_failure:
  - cat .tox/log/*
  - cat .tox/*/log/*
notifications:
  email:
    on_success: never
    on_failure: always
