language: python
python:
  - "3.8"
dist: xenial
cache: false
env:
  global:
    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - SEGFAULT_SIGNALS=all
    - LANG=en_US.UTF-8
before_install:
  - python --version
  - uname -a
install:
  - python -mpip install --progress-bar=off tox
  - virtualenv --version
  - pip --version
  - tox --version
script:
  - tox -v
after_failure:
  - cat .tox/log/*
  - cat .tox/*/log/*
notifications:
  email:
    on_success: never
    on_failure: always
