language: python
jobs:
  include:
    - name: "Python 3.10.0 on Xenial Linux"
      dist: xenial
      python: 3.10           # this works for Linux but is ignored on macOS or Windows
      env:
        - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
        - SEGFAULT_SIGNALS=all
        - LANG=en_US.UTF-8
      before_install:
        - python --version
        - uname -a
      cache: false
    - name: "Python 3.10.0 on macOS"
      os: osx
      osx_image: xcode11.3  # Python 3.10.0 running on macOS 10.14.6
      language: shell       # 'language: python' is an error on Travis CI macOS
      env:
        - LANG=en_US.UTF-8
        - PATH=$HOME/.pyenv/bin:$PATH
      before_install:
        - eval "$(pyenv init -)"
        - eval "$(pyenv virtualenv-init -)"
        - pyenv install -s 3.10.0
        - pyenv global 3.10.0
        - python --version
        - uname -a
      cache:
        directories:
          - /Users/travis/.pyenv/versions
install:
  - make
  - python -mpip install --progress-bar=off --upgrade pip
  - python -mpip install --progress-bar=off pipenv
  - pyenv rehash
  - pip --version
  - pipenv --version
  - virtualenv --version
  - pipenv install --dev
script:
  - make test
after_failure:
  - cat .tox/log/*
  - cat .tox/*/log/*
notifications:
  email:
    on_success: never
    on_failure: always
