view:
  row_number: bool(required=False)
  appearance: include('appearance', required=False)
  keymap: include('keymap', required=False)

---
appearance:
  theme: options('basic')

keymap:
  mode: options('basic', 'emacs', 'vim')
