####################################################
# Emacs Key Mappings
####################################################

# The `global_command_key` is a key prefix.
# Empty string means no `global_command_key`, while with a non-empty
# string, we will combine it with another key to define a single key
# action.
#
# E.g. in `emacs` mode, with `global_command_key` defined as `ctrl x`,
# key `ctrl x ctrl c` means exit Pyfx.
global_command_key: "ctrl x"

# Key Mappings for Autocomplete
autocomplete_popup:
  cursor_down: "meta n"
  cursor_up: "meta p"
  select: "enter"
  cancel: "ctrl g"

# Key Mappings for Help Page
help_popup:
  cursor_down: "ctrl n"
  cursor_up: "ctrl p"
  exit: "ctrl x 0"

# Key Mappings for Json Browser
json_browser:
  cursor_down: "ctrl n"
  cursor_up: "ctrl p"
  expand_all: "ctrl x e"
  collapse_all: "ctrl x c"
  toggle_expansion: "enter"
  open_query_bar: "meta x"
  open_help_page: "ctrl h"
  exit: "ctrl x ctrl c"

# Key Mappings for Query Bar
query_bar:
  query: "enter"
  cancel: "ctrl g"
