# `ui`
# All display and interaction (key mapping) related configuration.
ui:
  # `themes`
  # pre-defined themes name, accepted options are ["basic"]
  theme: "basic"

  # `keymap`
  # key mapping configurations
  keymap:
    # `mode`
    # pre-defined key mapping name, accepted options are ["basic", "emacs", "vim"]
    mode: "basic"
